import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/');
  await page.getByRole('combobox', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('playwright');
  await page.locator('iframe[name="a-oyfaszifqm9d"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('div').filter({ hasText: /^Verify$/ }).nth(2).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-oyfaszifqm9d"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.goto('https://www.google.com/search?q=playwright&sca_esv=1f9121a7cdf920c7&sxsrf=APpeQnvkWNXZbc1PZIO7o55n-1UXnReFLA%3A1789038457879&source=hp&ei=eY-iapqdNKDf4-EPr_HcuQE&iflsig=ABILxe8AAAAAaqKdid9OhENy23ZA5qE9MNPp-XFwEiHF&ved=0ahUKEwjavZTO7-OWAxWg7zgGHa84NxcQ4dUDCB0&uact=5&oq=playwright&gs_lp=Egdnd3Mtd2l6IgpwbGF5d3JpZ2h0MggQABiABBixAzIIEAAYgAQYsQMyCBAAGIAEGLEDMgUQABiABDIIEAAYgAQYsQMyBRAAGIAEMgUQABiABDIIEAAYgAQYtAcyCBAAGIAEGLEDMgUQABiABEjZHFDkBVj7FHABeACQAQCYAYQEoAHTDaoBCzYuMS4xLjAuMS4xsAEAuAEDyAEA-AEBmAILoAKADqgCCsICChAAGAMYjwEY6gLCAgsQABiABBixAxiDAcICBRAuGIAEwgILEC4YgAQYsQMYgwHCAggQLhiABBjlBMICCxAuGIAEGLEDGOUEwgILEAAYgAQYtAcYyQPCAgsQABiABBiKBRiSA5gDBuIDBBgAIF3iAwQYACBe4gMEGAAgX-IDBBgAIGDiAwQYACBh4gMEGAAgYvEFKdSemCL1Ez2SBwk3LjEuMS4wLjKgB_4-sgcJNi4xLjEuMC4yuAf5DcIHBTAuNy40yAcdgAgB&sclient=gws-wiz&sei=ro-iauubG5iXwcsPuKKDsAE');
  await page.getByRole('link', { name: 'Playwright: Fast and reliable' }).click();
  await page.getByRole('link', { name: 'Get started' }).click();
  await page.getByRole('link', { name: 'How to run the example test' }).click();
});